name: Usage Org
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: austenstone/dependabot-secrets-sync@main
        with:
          organization: octoaustenstone
          github-token: ${{ secrets.GHAS_POLICY_AS_CODE_TOKEN }}
          visibility: selected
          visibility-repos: |
            actions-angular
            vulnerable-node
          secrets-exclude: |
            GITHUB_TOKEN
            SUPER_SECRET
        env:
          SECRETS: ${{ toJson(secrets) }}
