name: Usage Org
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          organization: octoaustenstone
          github-token: ${{ secrets.GHAS_POLICY_AS_CODE_TOKEN }}
        env:
          SECRETS: ${{ toJson(secrets) }}
